#!/bin/bash
userhost=$(whoami)@$(hostname)
distro=$(cat /etc/os-release | grep PRETTY_NAME | sed 's/PRETTY_NAME="//g' | sed 's/"//g')
kernel=$(uname -r)
memtotal=$(/usr/bin/free -m | grep Mem | sed 's/Mem:            //g' | sed 's/        / /g' | cut -f1 --delimiter=' ')
memused=$(/usr/bin/free -m | grep Mem | sed 's/Mem:            //g' | sed 's/        / /g' | cut -f2 --delimiter=' ')
packages=$(expr $(ls -l /etc/ypm/pkg | wc -l ) - 1)
uptime=$(uptime -p | sed 's/up //g')
shell=$(echo -e $SHELL | sed 's|/usr/bin/||g')

echo -e

echo -e "   ,_____,     \e[0m$userhost\e[0m"
echo -e "   | . . |     \e[91mos          $distro\e[0m"
echo -e "   | ._, |     \e[92mkernel      $kernel\e[0m"
echo -e "   |-----|     \e[93mmem         $memtotal / $memused\e[0m"
echo -e "  / ,   , \    \e[94mpackages    $packages\e[0m"
echo -e "  |_'   '_|    \e[95muptime      $uptime\e[0m"
echo -e "   '--'--'     \e[96mshell       $shell\e[0m"

echo -e